### ISSUE TITLE
Sgemm crashes on Intel Platform when transA is false and transB is true

### ISSUE THREAD

**Issue by AlexHild** [clMathLibraries/clBLAS#62] opened 2015-02-03 09:24 UTC
Using Sgemm of clBlas version 2.3. with transA = false and transB = true results in clblasBuildProgramFailure on my machine when using Intel platform 4.5.0.8. On NVidia/AMD platform I do not get this error. Can anyone confirm this?

**Comment by AlexHild** [comment] 2015-02-03 09:29
After looking through the other issues again I found that this issue is the same than #53. The only difference seems to be that I get it on Intel instead of ARM platform.

**Comment by kknox** [comment] 2015-02-03 17:37
I don't have a Intel or ARM platform handy to reproduce on ( I'm working to get some).  What intel processor do you have?  Can you post the output of `clinfo` (from APP SDK) or whatever the intel equivalent is?  Also, if you have a simple unit test to demonstrate issue, that would save me time trying to reproduce your code.  If not, list all parameters passed into sgemm.

I do believe that this is a library issue creating a kernel with an invalid cast, that only certain runtimes appear to catch.

**Comment by AlexHild** [comment] 2015-02-04 08:52
I have an Intel Core i7-3770 CPU @ 3.40GHz. You find the output of clinfo below. The error comes when using one of the Intel(R) OpenCL platforms(OpenCL 1.2, OpenCL 2.0), while the same Sgemm command works on NVidia CUDA (same PC) and AMD platforms (on another PC).

Delivering a unit test is not easy in my case, here are my parameters:

order = clblasRowMajor
transA = clBlasNoTrans,
transB = clBlasTrans (using clBlasNoTrans works)
M = 127
N = 97
K = 127
alpha = 1.0f
A = Memory of size 127 x 65
offA = 0
lda = 65
B = Memory of size 97 x 65
offB = 0
ldb = 65
beta = 1.0f
C = Memory of size 127 x 97
offC = 0
ldc = 97
numCommandQueues = 1
commandQueues = 1 commandQueue
numEventsInWaitList = 3
eventWaitList = 3 clEvents

Output of clinfo:

Number of platforms:                             3
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 1.2
  Platform Name:                                 Intel(R) OpenCL
  Platform Vendor:                               Intel(R) Corporation
  Platform Extensions:                           cl_khr_icd cl_khr_global_int32_
base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomic
s cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir
cl_intel_exec_by_local_thread cl_khr_depth_images cl_khr_3d_image_writes cl_khr_
fp64 cl_khr_gl_sharing cl_intel_dx9_media_sharing cl_khr_dx9_media_sharing cl_kh
r_d3d11_sharing cl_khr_gl_sharing
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 1.1 CUDA 7.0.18
  Platform Name:                                 NVIDIA CUDA
  Platform Vendor:                               NVIDIA Corporation
  Platform Extensions:                           cl_khr_byte_addressable_store c
l_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query
cl_nv_pragma_unroll cl_nv_d3d9_sharing cl_nv_d3d10_sharing cl_khr_d3d10_sharing
cl_nv_d3d11_sharing cl_nv_copy_opts
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0
  Platform Name:                                 Experimental OpenCL 2.0 CPU Onl
y Platform
  Platform Vendor:                               Intel(R) Corporation
  Platform Extensions:                           cl_khr_icd cl_khr_global_int32_
base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomic
s cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir
cl_intel_exec_by_local_thread cl_khr_depth_images cl_khr_3d_image_writes cl_khr_
image2d_from_buffer cl_khr_fp64 cl_intel_dx9_media_sharing cl_khr_dx9_media_shar
ing cl_khr_d3d11_sharing cl_khr_gl_sharing


  Platform Name:                                 Intel(R) OpenCL
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_CPU
  Device ID:                                     32902
  Max compute units:                             8
  Max work items dimensions:                     3
    Max work items[0]:                           8192
    Max work items[1]:                           8192
    Max work items[2]:                           8192
  Max work group size:                           8192
  Preferred vector width char:                   1
  Preferred vector width short:                  1
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      16
  Native vector width short:                     8
  Native vector width int:                       4
  Native vector width long:                      2
  Native vector width float:                     8
  Native vector width double:                    4
  Max clock frequency:                           3400Mhz
  Address bits:                                  64
  Max memory allocation:                         8573857792
  Image support:                                 Yes
  Max number of images read arguments:           480
  Max number of images write arguments:          480
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    480
  Max size of kernel argument:                   3840
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               No
    Round to +ve and infinity:                   No
    IEEE754-2008 fused multiply-add:             No
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    262144
  Global memory size:                            34295431168
  Constant buffer size:                          131072
  Max number of constant args:                   480
  Local memory type:                             Global
  Local memory size:                             32768
WARNING: Linking two modules of different data layouts!
WARNING: Linking two modules of different target triples: C:\Program Files (x86)
\Common Files\Intel\OpenCL\bin\common\clbltfnshared.rtl: 'i686-pc-win32-elf' and
 'x86_64-pc-win32-elf'
  Kernel Preferred work group size multiple:     128
  Error correction support:                      0
  Unified memory for Host and Device:            1
  Profiling timer resolution:                    301
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     Yes
  Queue properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Platform ID:                                   00000000000C8560
  Name:                                                  Intel(R) Core(TM) i7-37
70 CPU @ 3.40GHz
  Vendor:                                        Intel(R) Corporation
  Device OpenCL C version:                       OpenCL C 1.2
  Driver version:                                4.5.0.8
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 (Build 8)
  Extensions:                                    cl_khr_icd cl_khr_global_int32_
base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomic
s cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir
cl_intel_exec_by_local_thread cl_khr_depth_images cl_khr_3d_image_writes cl_khr_
fp64 cl_khr_gl_sharing cl_intel_dx9_media_sharing cl_khr_dx9_media_sharing cl_kh
r_d3d11_sharing cl_khr_gl_sharing


  Platform Name:                                 NVIDIA CUDA
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Device ID:                                     4318
  Max compute units:                             8
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           64
  Max work group size:                           1024
  Preferred vector width char:                   1
  Preferred vector width short:                  1
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      1
  Native vector width short:                     1
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           719Mhz
  Address bits:                                  32
  Max memory allocation:                         536870912
  Image support:                                 Yes
  Max number of images read arguments:           256
  Max number of images write arguments:          16
  Max image 2D width:                            32768
  Max image 2D height:                           32768
  Max image 3D width:                            4096
  Max image 3D height:                           4096
  Max image 3D depth:                            4096
  Max samplers within kernel:                    32
  Max size of kernel argument:                   4352
  Alignment (bits) of base address:              4096
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               128
  Cache size:                                    131072
  Global memory size:                            2147483648
  Constant buffer size:                          65536
  Max number of constant args:                   9
  Local memory type:                             Scratchpad
  Local memory size:                             49151
  Kernel Preferred work group size multiple:     32
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1000
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Platform ID:                                   00000000027BFE30
  Name:                                          GeForce GTX 680MX
  Vendor:                                        NVIDIA Corporation
  Device OpenCL C version:                       OpenCL C 1.1
  Driver version:                                347.25
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.1 CUDA
  Extensions:                                    cl_khr_byte_addressable_store c
l_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query
cl_nv_pragma_unroll cl_nv_d3d9_sharing cl_nv_d3d10_sharing cl_khr_d3d10_sharing
cl_nv_d3d11_sharing cl_nv_copy_opts  cl_khr_global_int32_base_atomics cl_khr_glo
bal_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_ex
tended_atomics cl_khr_fp64


  Platform Name:                                 Experimental OpenCL 2.0 CPU Onl
y Platform
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_CPU
  Device ID:                                     32902
  Max compute units:                             8
  Max work items dimensions:                     3
    Max work items[0]:                           8192
    Max work items[1]:                           8192
    Max work items[2]:                           8192
  Max work group size:                           8192
  Preferred vector width char:                   1
  Preferred vector width short:                  1
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      16
  Native vector width short:                     8
  Native vector width int:                       4
  Native vector width long:                      2
  Native vector width float:                     8
  Native vector width double:                    4
  Max clock frequency:                           3400Mhz
  Address bits:                                  64
  Max memory allocation:                         8573857792
  Image support:                                 Yes
  Max number of images read arguments:           480
  Max number of images write arguments:          480
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    480
  Max size of kernel argument:                   3840
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               No
    Round to +ve and infinity:                   No
    IEEE754-2008 fused multiply-add:             No
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    262144
  Global memory size:                            34295431168
  Constant buffer size:                          131072
  Max number of constant args:                   480
  Local memory type:                             Global
  Local memory size:                             32768
  Kernel Preferred work group size multiple:     128
  Error correction support:                      0
  Unified memory for Host and Device:            1
  Profiling timer resolution:                    301
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     Yes
  Queue properties:
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Platform ID:                                   0000000002A833F0
  Name:                                                  Intel(R) Core(TM) i7-37
70 CPU @ 3.40GHz
  Vendor:                                        Intel(R) Corporation
  Device OpenCL C version:                       OpenCL C 2.0
  Driver version:                                4.6.0.92
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 2.0 (Build 99)
  Extensions:                                    cl_khr_icd cl_khr_global_int32_
base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomic
s cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir
cl_intel_exec_by_local_thread cl_khr_depth_images cl_khr_3d_image_writes cl_khr_
image2d_from_buffer cl_khr_fp64 cl_intel_dx9_media_sharing cl_khr_dx9_media_shar
ing cl_khr_d3d11_sharing cl_khr_gl_sharing

**Comment by vejja** [comment] 2015-02-07 12:37
Alex
I have exactly the same bug. Please see the comment I posted on #53.
I am using Apple's OpenCL framework, not Intel's SDK.

**Comment by pavanky** [comment] 2015-02-12 19:59
@AlexHild Are you running on the master branch or develop branch ?

**Comment by AlexHild** [comment] 2015-02-13 11:14
I am running the latest version of the develop branch.

2015-02-12 20:59 GMT+01:00 Pavan Yalamanchili <notifications@github.com>:

**Comment by AlexHild** [comment] 2015-02-13 14:53
Here is the buildInfo for the unsuccessful build:

Compilation started
2:98:63: error: can't convert between vector values of different size ('uint8' and 'unsigned long')
Compilation failed

**Comment by AlexHild** [comment] 2015-02-13 15:13
The seems to come from this line:

const uint8 bk = ((uint8)(0, 1, 2, 3, 4, 5, 6, 7) + ( get_group_id(0)*0 + k )) % Kbase;

Perhaps the problem is that get_group_id() is unsigned int on some systems (CL_DEVICE_ADDRESS_BITS = 32), but unsigned long on others(CL_DEVICE_ADDRESS_BITS = 64)?

**Comment by vejja** [comment] 2015-02-13 15:29
Alex
In my case error was coming from line 

```
<program source>:97:51: error: Cannot downconvert and widen scalar type 'unsigned long' to vector type '__uint4'
            const uint4 bk = ((uint4)(0, 1, 2, 3) + (( get_group_id(0)*0 + k ) >> 1)) % vKB;
                              ~~~~~~~             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

So very similar to yours...
And as I noted in my comment, I am very sure this only happens when the matrix has more than 8 columns.

**Comment by AlexHild** [comment] 2015-02-13 15:41
@vejja: What is the value of CL_DEVICE_ADDRESS_BITS on your system?

**Comment by pavanky** [comment] 2015-02-13 15:59
@AlexHild This is interesting. I was facing a similar problem on Intel a couple of months ago. I sent in a patch that resolved this. What OS are you using ?

**Comment by AlexHild** [comment] 2015-02-13 16:00
@pavanky I am using Windows 7.

**Comment by pavanky** [comment] 2015-02-13 16:01
@vejja The OSX issue may be slightly different. I think that particular issue is reported somewhere else and is being worked on.

**Comment by pavanky** [comment] 2015-02-13 16:02
@AlexHild We have a Windows 8 machine in house. I will give this a shot. Can you also list the intel sdk version you are using ?

**Comment by vejja** [comment] 2015-02-13 16:05
@AlexHild : 64 bits. Spot on.
@pavanky : I also have Windows 8 with Intel SDK. Let me give it a quick shot right now.

**Comment by AlexHild** [comment] 2015-02-13 16:10
@pavanky I just installed the newest Intel SDK included in Intel INDE 2015. The driver version is 5.0.0.43 (OpenCL 2.0(Build 156)). The same issue with 4.5.0.8(OpenCL 1.2 (Build 8)).

**Comment by AlexHild** [comment] 2015-02-13 16:15
Same issue with 5.0.0.57, which you can get here: http://registrationcenter.intel.com/irc_nas/5198/opencl_runtime_15.1_x64_setup.msi

**Comment by pavanky** [comment] 2015-02-13 16:17
> Perhaps the problem is that get_group_id() is unsigned int on some systems (CL_DEVICE_ADDRESS_BITS = 32), but unsigned long on others(CL_DEVICE_ADDRESS_BITS = 64)? Casting from unsigned long to uint8 is not part of the standard as far as I know, but seems to work when using the AMD compiler on a CPU with (CL_DEVICE_ADDRESS_BITS = 64).

I get the `CL_DEVICE_ADDRESS_BITS=64` on my Linux machine as well. We are using clBLAS in our library (arrayfire) and are testing this with the given configurations. So far the only failures we have seen are on OSX. I can try to see if our tests are passing on Windows.

**Comment by pavanky** [comment] 2015-02-13 16:21
Alright, we are able to reproduce this on Windows. The problem does not seem to exist on Linux.

**Comment by vejja** [comment] 2015-02-13 16:21
Just tested on Windows 8 + Intel's OpenCL SDK, and it crashes as beautifully as with OSX + Apple's OpenCL framework.

```
Build log:

WARNING: -s is not supported on the Intel OpenCL GPU device.
:95:63: error: can't convert between vector values of different size ('uint8' an
d 'unsigned long')
            const uint8 bk = ((uint8)(0, 1, 2, 3, 4, 5, 6, 7) + ( get_group_id(0
)*0 + k )) % Kbase;
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~

error: front end compiler failed build.
```

To me this looks like a bug in clBLAS's implementation of SGEMM, not an Intel/Microsoft/Apple issue. 
Otherwise we would run into some similar problems when running SGEMM without _clBlasTrans_ set.

**Comment by pavanky** [comment] 2015-02-13 16:23
@vejja @AlexHild Thanks for taking time to narrow it down. I will try and fix this issue.

**Comment by AlexHild** [comment] 2015-02-13 16:25
My guess is that some compilers allow implicitly casting ulong to uint8, while others do not. I think the specs do not require this cast to work.

**Comment by vejja** [comment] 2015-02-13 17:09
@AlexHild 
You've got to be right.
I wrote a very simple kernel that does
```
const uint test1 = get_group_id(0);
const uint8 test2 = get_group_id(0);
const uint test3 = (uint)42 +  get_group_id(0);
const uint8 test4 = (uint8)42 + get_group_id(0);
```
the first three tests run OK, but test4 crashes with error
```
error CL: can't convert between vector values of different size ('uint8' and 'size_t' (aka 'unsigned long'))
          const uint8 test2 = (uint8)42 + get_group_id(0);
                              ~~~~~~~~~ ^ ~~~~~~~~~~~~~~~
  
INTEL_OPENCL_BUILD_RULES : error : front end compiler failed build.
```
Just to be sure I checked and explicit casting works fine as
```
const uint test5 = (uint)get_global_id(0);
const uint8 test6 = (uint8)get_global_id(0);
```
both compile and run ok.

**Comment by pavanky** [comment] 2015-02-13 18:53
@vejja @AlexHild 

Can you make the following changes to see if it fixes the issue ?  Both changes are done in the same file: `src/library/blas/gens/gemm.c`

Change line 560 to look like this: 

```
       sprintf(globalIdB, "(uint)get_global_id(%d)", 1-i);
```

Change line 758 to look like this:

```
ksprintf(&exprK, "( (uint)(get_group_id(0))*%lu + k )", staggered/vecLenA*vecLenA);
```

If this works, I will send in a pull request and @TimmyLiu or @kknox can review / merge it

**Comment by pavanky** [comment] 2015-02-13 21:09
I verified that it works on windows. I sent in a pull request.

**Comment by AlexHild** [comment] 2015-02-16 08:23
For me theses changes fix the issue. Thanks @pavanky !

**Comment by pavanky** [comment] 2015-02-16 19:20
The patch has been merged into develop.

**Closed by pavanky** 2015-02-16 19:20 UTC
Labels: Apple, bug, CPU, GPU, Intel, OSX, Windows

**Comment by vejja** [comment] 2015-02-17 20:08
I can confirm this also fixed the issue on Mac OS X
Thanks
