### ISSUE TITLE
Build fails on OSX with XCode 7.1 because "embedding a #pragma directive within macro arguments is not supported"

### ISSUE THREAD

**Issue by GOFAI** [clMathLibraries/clBLAS#188] opened 2015-11-17 03:18 UTC
I have no trouble building using XCode 6, but the latest version is more stringent and fails on a few files because "embedding a #pragma directive within macro arguments is not supported."

```
In file included from /tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/xtrsm.cc:29:
In file included from /tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/trtri/TrtriKernelSourceIncludes.h:5:
In file included from /tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/trtri/TrtriKernelSourceIncludes.cpp:22:
/tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/trtri/diag_dtrtri_upper_128_16.cpp:62:4: error: embedding a #pragma directive within macro arguments is not supported
  #pragma unroll \n
   ^
/tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/trtri/diag_dtrtri_upper_128_16.cpp:114:6: error: embedding a #pragma directive within macro arguments is not supported
    #pragma unroll\n
     ^
/tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/trtri/diag_dtrtri_upper_128_16.cpp:142:2: error: embedding a #pragma directive within macro arguments is not supported
#pragma unroll\n
 ^
In file included from /tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/xtrsm.cc:29:
In file included from /tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/trtri/TrtriKernelSourceIncludes.h:5:
In file included from /tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/trtri/TrtriKernelSourceIncludes.cpp:33:
/tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/trtri/diag_dtrtri_lower_128_16.cpp:65:2: error: embedding a #pragma directive within macro arguments is not supported
#pragma unroll\n
 ^
/tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/trtri/diag_dtrtri_lower_128_16.cpp:141:2: error: embedding a #pragma directive within macro arguments is not supported
#pragma unroll\n
 ^
/tmp/clblas20151115-84503-1lfrpf0/clBLAS-2.8/src/library/blas/trtri/diag_dtrtri_lower_128_16.cpp:166:2: error: embedding a #pragma directive within macro arguments is not supported
#pragma unroll\n
 ^
9 errors generated.
make[2]: *** [library/CMakeFiles/clBLAS.dir/blas/xtrsm.cc.o] Error 1
make[1]: *** [library/CMakeFiles/clBLAS.dir/all] Error 2
```
The macro in question is ```STRINGIFY(...)```.

**Comment by GOFAI** [comment] 2015-11-17 03:26
Is it possible to do something like ```_Pragma("unroll")``` here, given that ```STRINGIFY(...)``` is producing an OpenCL kernel?

**Comment by hughperkins** [comment] 2015-11-17 05:17
Probably best to check the opencl specs, rather than just trying it.  Otherwise it will work on some platforms, and not on others.  From opencl 1.1 specs, sectoin 6.9, I only see:

```
6.9
Preprocessor Directives and Macros
The preprocessing directives defined by the C99 specification are supported.
The # pragma directive is described as:
# pragma pp-tokens opt new-line
A # pragma directive where the preprocessing token OPENCL (used instead of STDC ) does not
immediately follow pragma in the directive (prior to any macro replacement) causes the
implementation to behave in an implementation-defined manner. The behavior might cause
translation to fail or cause the translator or the resulting program to behave in a non-conforming
manner. Any such pragma that is not recognized by the implementation is ignored. If the
preprocessing token OPENCL does immediately follow pragma in the directive (prior to any
macro replacement), then no macro replacement is performed on the directive, and the directive
shall have one of the following forms whose meanings are described elsewhere:
#pragma OPENCL FP_CONTRACT on-off-switch
on-off-switch: one of ON OFF DEFAULT
#pragma OPENCL EXTENSION extensionname : behavior
#pragma OPENCL EXTENSION all : behavior
The following predefined macro names are available.
__FILE__ The presumed name of the current source file (a character string literal).
__LINE__ The presumed line number (within the current source file) of the current
source line (an integer constant).
__OPENCL_VERSION__ substitutes an integer reflecting the version number of the OpenCL
supported by the OpenCL device. The version of OpenCL described in this document will have
__OPENCL_VERSION__ substitute the integer 110.
CL_VERSION_1_0 substitutes the integer 100 reflecting the OpenCL 1.0 version.
CL_VERSION_1_1 substitutes the integer 110 reflecting the OpenCL 1.1 version.
__ENDIAN_LITTLE__ is used to determine if the OpenCL device is a little endian architecture
or a big endian architecture (an integer constant of 1 if device is little endian and is undefined
otherwise). Also refer to CL_DEVICE_ENDIAN_LITTLE specified in table 4.3.
__kernel_exec(X, typen) (and kernel_exec(X, typen)) is defined as
Last Revision Date: 6/1/11
Page 196__kernel __attribute__((work_group_size_hint(X, 1, 1))) \
__attribute__((vec_type_hint(typen)))
__IMAGE_SUPPORT__ is used to determine if the OpenCL device supports images. This is an
integer constant of 1 if images are supported and is undefined otherwise. Also refer to
CL_DEVICE_IMAGE_SUPPORT specified in table 4.3.
__FAST_RELAXED_MATH__ is used to determine if the –cl-fast-relaxed-math optimization
option is specified in build options given to clBuildProgram. This is an integer constant of 1 if
the –cl-fast-relaxed-math build option is specified and is undefined otherwise.
The macro names defined by the C99 specification but not currently supported by OpenCL are
reserved for future use.
```

**Comment by hughperkins** [comment] 2015-11-17 05:23
Just in case it's useful, what I did in DeepCL, to stringify things, was to use Python, combined with cogapp http://nedbatchelder.com/code/cog/  eg:

https://github.com/hughperkins/DeepCL/blob/master/src/conv/BackpropWeightsNaive.cpp#L52-L138

```
    // [[[cog
    // import stringify
    // stringify.write_kernel2("kernel", "cl/backpropweights.cl", "backprop_floats", 'options')
    // ]]]
    // generated using cog, from cl/backpropweights.cl:
    const char * kernelSource =  
    "// Copyright Hugh Perkins 2014,2015 hughperkins at gmail\n"
    "//\n"

    ...

    "\n"
    "\n"
    "";
    kernel = cl->buildKernelFromString(kernelSource, "backprop_floats", options, "cl/backpropweights.cl");
    // [[[end]]]
```

**Comment by GOFAI** [comment] 2015-11-17 05:31
I would certainly prefer to work with Python than try to fight the C++ preprocessor like this. The spec is ambiguous, and Googling doesn't seem to find any example of ```_Pragma``` in an OpenCL kernel, which suggests we can't count on its availability.

**Comment by GOFAI** [comment] 2015-11-20 08:55
On OSX, at least, ```_Pragma()``` seems to work in OpenCL kernels. Might it be reasonable to define some sort of platform-specific macro that uses ```_Pragma("unroll")``` on OSX and leaves it as ```#pragma unroll``` in other cases where it might be necessary?

**Comment by TimmyLiu** [comment] 2015-11-20 15:15
I am not sure if you saw pull request #189 is addressing this problem. I think it should work but we need to at least test it on linux and windows.before merging the PR.

**Comment by hughperkins** [comment] 2015-11-21 11:01
One other possible variant, in case #189 is not portable (which it might be, I dont know), could be to replace `#pragma` with `%PRAGMA`, then to search and replace `%PRAGMA` with `#pragma` at runtime.  There is already precedent for such search and replace in clBLAS, eg for %VTYPE and similar.

**Comment by TimmyLiu** [comment] 2015-11-25 16:08
PR #189 is merged. Can you verify if this fixed the compile time error for you?

**Comment by GOFAI** [comment] 2015-11-25 18:17
I'm not in an easy position to check this myself--2.8 always compiled fine for me, but it turns out that was because I'm still using XCode 6.4. When I submitted a pull request to homebrew to bump the clBLAS formula from 2.2. to 2.8, their testing discovered the problem with XCode 7.1 problem that I reported.

**Comment by hughperkins** [comment] 2015-11-25 23:28
Hi Edward, following your example (and basically hacking and pasting your formula :-) ), created a travis/brew build for clblas at https://github.com/hughperkins/homebrew-test-travis-osx/blob/c63c4682eb062d0c8dc43cdec787b6270a7e22e9/Formula/clblas.rb will see how it fairs: https://travis-ci.org/hughperkins/homebrew-test-travis-osx/builds

**Comment by hughperkins** [comment] 2015-11-25 23:34
Seems built ok? https://travis-ci.org/hughperkins/homebrew-test-travis-osx/builds/93268172#L3232

**Comment by GOFAI** [comment] 2015-11-25 23:37
Looks like it.

**Comment by hughperkins** [comment] 2015-11-25 23:37
k.  Is it an appropriate xcode version being used here?

**Comment by GOFAI** [comment] 2015-11-25 23:40
It's definitely using a higher version than the one I have on my MacBook.

**Comment by TimmyLiu** [comment] 2015-12-03 15:15
Can we close this issue? It seems Hugh was able to verify that it builds for xcode 7.0?

**Comment by gaming-hacker** [comment] 2016-02-10 05:18
this is broken and not building, look at the latest travis

**Comment by pavanky** [comment] 2016-02-10 06:45
@gaming-hacker This is most likely fixed in develop branch from the [recent PR](https://github.com/clMathLibraries/clBLAS/pull/216). Can you test this out ?

**Comment by jainanshul** [comment] 2016-03-15 19:20
@pavanky The issue is resolved in the develop branch of this project.

**Comment by hughperkins** [comment] 2016-03-28 11:03
I think this can be closed now.  Seems like that it works now in 'develop' branch is sufficient?

**Closed** 2016-03-28 11:54 UTC
